### ISSUE TITLE
EntityContext?

### ISSUE THREAD

**Issue by alexdresko** [abatishchev/Elmah.Contrib.EntityFramework#2]
> You can use either EntityErrorLog (requires providerName="System.Data.EntityClient") or EntityContext (requires providerName="System.Data.SqlClient") but not both.

EntityContext is not a type in this code...

**Comment by abatishchev** [comment]
Indeed, a typo. Use `ElmahContext`.

**Comment by alexdresko** [comment]
I tried this earlier and got an exception about ElmahContext not having a constructor... 

```
<configuration>
    <connectionStrings>
        <add name="ModelContainer" connectionString="metadata=res://*/;provider=System.Data.SqlClient;provider connection string=&quot;Data Source=localhost;Initial Catalog=Northwind;Integrated Security=True;&quot;" providerName="System.Data.EntityClient" />
    </connectionStrings>
    <elmah>
        <errorLog type="Elmah.Contrib.EntityFramework.ElmahContext, Elmah.Contrib.EntityFramework" connectionStringName="ModelContainer" />
    </elmah>
</configuration>
```

I can try again if you need a more detailed error message to reproduce.

**Comment by abatishchev** [comment]
Please check what type supports what provider. You're using EntityClient apparently.

**Comment by alexdresko** [comment]
I don't quite understand... Here's my connection string.. 

        <add name="DefaultConnection" connectionString="Data Source=(LocalDb)\MSSQLLocalDB;Initial Catalog=aspnet-BenefactorsRegistration-20160307011453;Integrated Security=True" providerName="System.Data.SqlClient" />

**Comment by abatishchev** [comment]
In the code snippet above your connection string is:

    <add name="ModelContainer" connectionString="metadata=res://*/;provider=System.Data.SqlClient;provider connection string=&quot;Data Source=localhost;Initial Catalog=Northwind;Integrated Security=True;&quot;" providerName="System.Data.EntityClient" />

I don't quite understand either ;)

**Comment by alexdresko** [comment]
haha.. sorry, I copy/pasted my example from your readme.md and just changed the context.. I've already reverted those changes in source control, so I was trying to save myself some effort.. here's what mine would have really looked like (roughly) with ElmahContext... 

```
<configuration>
    <connectionStrings>
        <add name="DefaultConnection" connectionString="Data Source=(LocalDb)\MSSQLLocalDB;Initial Catalog=aspnet-BenefactorsRegistration-20160307011453;Integrated Security=True" providerName="System.Data.SqlClient" />
    </connectionStrings>
    <elmah>
        <errorLog type="Elmah.Contrib.EntityFramework.ElmahContext, Elmah.Contrib.EntityFramework" connectionStringName="ModelContainer" />
    </elmah>
</configuration>
```

**Comment by abatishchev** [comment]
`connectionStringName="<your connection string name goes here>"`.

**Comment by alexdresko** [comment]
I have done that as well..  Maybe this screenshot will help. 

![image](https://cloud.githubusercontent.com/assets/333022/13755815/5e2fca1a-e9f3-11e5-9328-1d93b24d102c.png)

**Comment by abatishchev** [comment]
Oh, I see.
Don't write to Elmah using the lib, this would add an unnecessary layer. Use the built-in `SqlErrorLog` instead.
Read from Elmah using the lib, strongly-typed entities definitely would help.

**Comment by alexdresko** [comment]
I'm not writing to Elmah... I get this error when I view elmah.axd with the configuration specified.

**Comment by abatishchev** [comment]
Don't register `EntiyErrorLog` within Elmah. Let it use `SqlErrorLog` for both writing to db and reading from db. Use my one to read errors programmatically, where you would be really benefited from strongly-typed entities.
